modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[modproperties.${mod_id}]
dominionsword_addon=true
dominionsword_addon_name_zh_cn="\\u7edf\\u5fa1\\u4e4b\\u5251\\uff1a\\u5353\\u8d8a\\u524d\\u7ebf\\u517c\\u5bb9"
dominionsword_addon_name_en_us="Dominion Sword: Superb Warfare Compatibility"
dominionsword_addon_name_ja_jp="\\u30c9\\u30df\\u30cb\\u30aa\\u30f3\\u30bd\\u30fc\\u30c9\\uff1aSuperb Warfare\\u4e92\\u63db"

[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="dominionsword"
mandatory=true
versionRange="[1.37.0-beta.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="superbwarfare"
mandatory=true
versionRange="[0.8.9,)"
ordering="AFTER"
side="BOTH"
